
name: Run Script

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  workflow_dispatch:

jobs:
  revanced-cli-script:
    runs-on: ubuntu-latest

    steps:
      
      #This is only necessary for the workflow
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
 
        # Get youtube apk and place it in build folder
      - name: Download YouTube apk
        run: |
          mkdir "build"
          cd "build"
          wget "https://github.com/CnC-Robert/revanced-cli-script/releases/download/stock-yt/youtube.apk"
          cd ..
      
      # Run script
      - name: Execute script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./build-from-source.sh
          ./build-from-source.sh
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: vanced
          path: |
            revanced.apk
            revanced-clis.jar
